/**
 * Site chrome (header, footer) emitted into `components/chrome.tsx`.
 *
 * Kept separate from the section library because the header and footer are
 * driven by their own specs and appear once per page, not once per section.
 *
 * The mobile navigation uses a CSS-only disclosure (a checkbox + sibling
 * selector) rather than a client component, so the generated site ships no
 * hydration-sensitive JavaScript beyond what Next.js itself requires.
 */

export const CHROME_TSX = String.raw`/**
 * Site header and footer. Generated by Sitewright from the measured page.
 */
import { siteSpec } from "../lib/site-spec";
import type { Link } from "../lib/types";

function assetSrc(localPath: string): string {
  return (localPath.startsWith("/") ? localPath : "/" + localPath).replace(/\/{2,}/g, "/");
}

function hrefFor(l: Link): string {
  return l.href && l.href.length ? l.href : "#";
}

function ext(l: Link) {
  return l.external ? { target: "_blank", rel: "noopener noreferrer" } : {};
}

/**
 * Reduce an href to something safe to render.
 *
 * By the time a link reaches here it has already been through the spec builder,
 * which sanitises every href read off the crawled page. This is a second, local
 * check rather than a shared import because the generated project is standalone
 * and cannot import from the tool that produced it. The rule is an allowlist,
 * matching the one applied at the boundary.
 */
function safeHref(href: string): string {
  const h = (href || "").trim();
  if (!h) return "#";
  if (h.startsWith("#") || h.startsWith("/") || h.startsWith("?")) return h;
  try {
    if (!/^(https?|mailto|tel|sms):/i.test(new URL(h).protocol)) return "#";
  } catch {
    return h;
  }
  return h;
}

export function Brand() {
  const nav = siteSpec.nav;
  const title = nav?.brandText || nav?.brand || siteSpec.meta.title;
  if (!nav) return null;
  return (
    <a href="#" className="sw-brand" aria-label={title}>
      {nav.logo && nav.logo.localPath ? (
        <img
          src={assetSrc(nav.logo.localPath)}
          alt=""
          className="sw-brand-mark"
          width={nav.logo.intrinsicWidth || nav.logo.width || undefined}
          height={nav.logo.intrinsicHeight || nav.logo.height || 28}
        />
      ) : null}
      {title ? <span className="sw-brand-text">{title}</span> : null}
    </a>
  );
}

export function SiteHeader() {
  const nav = siteSpec.nav;
  if (!nav) return null;
  const links = nav.links.slice(0, 10);
  const style: React.CSSProperties = {
    background: nav.background && nav.background !== "transparent" ? nav.background : undefined,
    borderBottom: nav.borderBottom && nav.borderBottom !== "none" ? nav.borderBottom : undefined,
  };
  if (nav.variant === "centered") {
    return (
      <header className="sw-header sw-header-centered" style={style}>
        <div className="sw-container">
          <div className="py-5 text-center">
            <Brand />
            {links.length ? (
              <nav className="mt-4 flex flex-wrap justify-center gap-x-6 gap-y-2 text-sm" aria-label="Main">
                {links.map((l, i) => (
                  <a key={i} href={safeHref(l.href)} {...ext(l)}>
                    {l.label}
                  </a>
                ))}
              </nav>
            ) : null}
          </div>
        </div>
      </header>
    );
  }
  if (nav.variant === "minimal" || nav.variant === "stacked") {
    return (
      <header className="sw-header" style={style}>
        <div className="sw-container flex items-center justify-between gap-6 py-5">
          <Brand />
          {nav.cta ? (
            <a className="sw-btn sw-btn-primary" href={safeHref(nav.cta.href)} {...ext(nav.cta)}>
              {nav.cta.label}
            </a>
          ) : null}
        </div>
      </header>
    );
  }
  return (
    <header className={"sw-header" + (nav.sticky ? " sw-header-sticky" : "")} style={style}>
      <div className="sw-container flex items-center justify-between gap-6 py-4">
        <Brand />
        <nav className="sw-desktop-nav" aria-label="Main">
          {links.map((l, i) => (
            <a key={i} href={safeHref(l.href)} {...ext(l)}>
              {l.label}
            </a>
          ))}
          {nav.cta ? (
            <a className="sw-btn sw-btn-primary sw-nav-cta" href={safeHref(nav.cta.href)} {...ext(nav.cta)}>
              {nav.cta.label}
            </a>
          ) : null}
        </nav>
        <input type="checkbox" id="sw-nav-toggle" className="sw-nav-checkbox" aria-hidden="true" tabIndex={-1} />
        <label htmlFor="sw-nav-toggle" className="sw-nav-burger" aria-label="Toggle navigation">
          <span />
          <span />
          <span />
        </label>
        <div className="sw-mobile-nav">
          <nav aria-label="Mobile">
            {links.map((l, i) => (
              <a key={i} href={safeHref(l.href)} {...ext(l)}>
                {l.label}
              </a>
            ))}
            {nav.cta ? (
              <a className="sw-btn sw-btn-primary" href={safeHref(nav.cta.href)} {...ext(nav.cta)}>
                {nav.cta.label}
              </a>
            ) : null}
          </nav>
        </div>
      </div>
    </header>
  );
}

export function SiteFooter() {
  const f = siteSpec.footer;
  if (!f) return null;
  const style: React.CSSProperties = {
    background: f.background && f.background !== "transparent" ? f.background : undefined,
    color: f.color && f.color !== "inherit" ? f.color : undefined,
    paddingTop: f.paddingY,
    paddingBottom: f.paddingY,
  };
  const cols = f.columns.filter((c) => c.links.length || c.heading);
  if (f.variant === "simple" || (f.variant !== "centered" && cols.length === 0)) {
    return (
      <footer className="sw-footer sw-footer-simple" style={style}>
        <div className="sw-container">
          <div className="flex flex-wrap items-center justify-between gap-6">
            <div>
              {f.brandText ? <p className="font-semibold">{f.brandText}</p> : null}
              {f.tagline ? (
                <p className="mt-1 text-sm" style={{ color: "var(--color-muted)" }}>
                  {f.tagline}
                </p>
              ) : null}
            </div>
            <nav className="flex flex-wrap gap-x-6 gap-y-2 text-sm" aria-label="Footer">
              {f.legal.map((l, i) => (
                <a key={i} href={safeHref(l.href)} {...ext(l)}>
                  {l.label}
                </a>
              ))}
            </nav>
          </div>
          {f.copyright ? (
            <p className="mt-8 text-xs" style={{ color: "var(--color-muted)" }}>
              {f.copyright}
            </p>
          ) : null}
        </div>
      </footer>
    );
  }
  return (
    <footer
      className={"sw-footer" + (f.variant === "centered" ? " sw-footer-centered" : "")}
      style={style}
    >
      <div className="sw-container">
        <div className={"grid gap-10 " + (f.variant === "centered" ? "text-center justify-items-center" : "md:grid-cols-[1.5fr_repeat(auto-fit,minmax(140px,1fr))]")}>
          <div>
            {f.brandText ? <p className="text-lg font-semibold">{f.brandText}</p> : null}
            {f.tagline ? (
              <p className="mt-2 max-w-sm text-sm" style={{ color: "var(--color-muted)" }}>
                {f.tagline}
              </p>
            ) : null}
          </div>
          {cols.map((c, i) => (
            <nav key={i} aria-label={c.heading || "Footer"}>
              {c.heading ? (
                <h2 className="mb-3 text-sm font-semibold uppercase tracking-wider" style={{ color: "var(--color-muted)" }}>
                  {c.heading}
                </h2>
              ) : null}
              <ul className="space-y-2 text-sm">
                {c.links.slice(0, 10).map((l, li) => (
                  <li key={li}>
                    <a href={safeHref(l.href)} {...ext(l)}>
                      {l.label}
                    </a>
                  </li>
                ))}
              </ul>
            </nav>
          ))}
        </div>
        <div className="mt-12 flex flex-wrap items-center justify-between gap-4 border-t pt-6 text-xs" style={{ borderColor: "var(--color-border)", color: "var(--color-muted)" }}>
          <span>{f.copyright}</span>
          <nav className="flex flex-wrap gap-x-6 gap-y-2" aria-label="Legal">
            {f.legal.map((l, i) => (
              <a key={i} href={safeHref(l.href)} {...ext(l)}>
                {l.label}
              </a>
            ))}
          </nav>
        </div>
      </div>
    </footer>
  );
}
`;

/**
 * Component-level CSS that the section library relies on. Appended to
 * `globals.css` so the whole design system lives in one stylesheet.
 */
export const CHROME_CSS = String.raw`
@layer components {
  .sw-section { position: relative; }
  .sw-section + .sw-section { margin-top: 0; }

  .sw-brand { display: inline-flex; align-items: center; gap: 0.6rem; text-decoration: none; font-weight: 700; }
  .sw-brand-mark { max-height: 28px; width: auto; }
  .sw-brand-text { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 40vw; }

  .sw-header-sticky { position: sticky; top: 0; z-index: 50; }

  .sw-desktop-nav { display: none; align-items: center; gap: 1.5rem; font-size: 0.9375rem; }
  .sw-desktop-nav a { text-decoration: none; }
  .sw-desktop-nav a:hover { color: var(--color-primary); }
  .sw-nav-cta { padding: 0.5rem 1rem; }

  .sw-nav-checkbox { position: absolute; opacity: 0; pointer-events: none; }
  .sw-nav-burger {
    display: inline-flex; flex-direction: column; justify-content: center; gap: 4px;
    width: 40px; height: 40px; padding: 8px; cursor: pointer; border-radius: var(--radius-sm);
  }
  .sw-nav-burger span { display: block; height: 2px; width: 100%; background: currentColor; border-radius: 2px; }
  .sw-mobile-nav { display: none; }

  .sw-hero-bg {
    position: absolute; inset: 0; z-index: -1;
    background-size: cover; background-position: center;
  }
  .sw-cta-band {
    background-image: linear-gradient(135deg, var(--color-primary) 0%, var(--color-accent) 100%);
    color: var(--color-on-primary);
  }
  .sw-cta-band h2, .sw-cta-band p { color: inherit; }

  .sw-announce { padding-top: 0.5rem !important; padding-bottom: 0.5rem !important; }

  .sw-card-flat { background: transparent; border: 1px solid var(--color-border); border-radius: var(--radius-lg); }
  .sw-badge {
    display: inline-block; padding: 0.15rem 0.55rem; border-radius: var(--radius-pill);
    background: color-mix(in srgb, var(--color-primary) 14%, transparent);
    font-size: 0.75rem; font-weight: 600;
  }
  .sw-row + .sw-row { border-top: 1px solid var(--color-border); }

  .sw-faq summary {
    display: flex; align-items: center; justify-content: space-between; gap: 1rem;
    padding: 1rem 1.25rem; cursor: pointer; font-weight: 600; list-style: none;
  }
  .sw-faq summary::-webkit-details-marker { display: none; }
  .sw-faq-icon { transition: transform 150ms ease; }
  .sw-faq[open] .sw-faq-icon { transform: rotate(45deg); }
  .sw-faq-body { padding: 0 1.25rem 1.25rem; color: var(--color-muted); }

  .sw-input {
    padding: 0.6rem 0.75rem; border-radius: var(--radius-md);
    border: var(--border-w) solid var(--color-border);
    background: var(--color-bg); color: var(--color-text);
  }
  .sw-input:focus-visible { outline: 2px solid var(--color-primary); outline-offset: 1px; }
}

@media (min-width: 900px) {
  .sw-desktop-nav { display: flex; }
  .sw-nav-burger { display: none; }
  .sw-mobile-nav { display: none !important; }
}

@media (max-width: 899px) {
  .sw-nav-checkbox:checked ~ .sw-mobile-nav { display: block; }
  .sw-mobile-nav {
    position: absolute; left: 0; right: 0; top: 100%;
    background: var(--color-bg); border-bottom: var(--border-w) solid var(--color-border);
    padding: 1rem var(--gutter) 1.5rem; box-shadow: var(--shadow-md);
  }
  .sw-header { position: relative; }
  .sw-mobile-nav nav { display: flex; flex-direction: column; gap: 0.75rem; }
  .sw-mobile-nav a { text-decoration: none; }
}
`;
