/**
 * Code generation: WebsiteSpec → a standalone Next.js project.
 *
 * Two modes, both validated by the same build step:
 *
 *   spec     (default) `app/page.tsx` maps the spec's sections through the
 *            section library. Deterministic: it cannot produce a broken file.
 *            The model's influence is already in the spec and in the page
 *            composition order.
 *
 *   ai-page  the model is additionally asked to author `app/page.tsx` as JSX
 *            over the provided components. If the build fails, the validator's
 *            bounded repair loop runs; if that still fails, the page falls back
 *            to `spec` mode. The model can improve the layout and it can never
 *            ship a broken build.
 *
 * Both modes write the same component library, the same types, and the same
 * design tokens, so a switch between them changes only one file.
 */

import path from "node:path";
import { createLogger } from "../logger";
import { config } from "../config";
import type { WebsiteSpec } from "../spec/schema";
import { CHROME_CSS, CHROME_TSX } from "./chrome";
import {
  gitignore,
  layoutTsx,
  nextConfig,
  nextEnv,
  packageJson,
  postcssConfig,
  scaffoldProject,
  tsconfig,
  typesTs,
  type ScaffoldFile,
} from "./scaffold";
import { SECTIONS_TSX } from "./sections";
import { renderGlobalsCss, sanitizeCssValue, themeHeader } from "./theme";

const log = createLogger("generator");

export type GenerationMode = "spec" | "ai-page";

export interface GenerateInput {
  spec: WebsiteSpec;
  projectDir: string;
  /** Slug used in the generated package name. */
  slug: string;
  /** Page composition: ordered section ids, from AI or deterministic fallback. */
  composition: { kind: string; id: string; props?: Record<string, unknown> }[];
  /** Authored `app/page.tsx`, when mode is `ai-page` and the model produced one. */
  authoredPage?: string;
  mode?: GenerationMode;
}

export interface GenerateOutput {
  projectDir: string;
  files: string[];
  changed: number;
  mode: GenerationMode;
  pageSource: "ai" | "spec";
}

export async function generateProject(input: GenerateInput): Promise<GenerateOutput> {
  const mode: GenerationMode = input.mode ?? (config().ai.mode as GenerationMode) ?? "spec";
  const { spec, projectDir } = input;

  const specModule = renderSpecModule(spec);
  const css = [
    themeHeader(spec.meta.sourceUrl, spec.stats.model || "the source page"),
    renderGlobalsCss(spec.theme),
    CHROME_CSS,
  ].join("\n");

  const useAi = mode === "ai-page" && !!input.authoredPage?.trim();
  const page = useAi
    ? normaliseAiPage(input.authoredPage as string)
    : deterministicPage(spec, input.composition);

  const files: ScaffoldFile[] = [
    { rel: "package.json", contents: packageJson(input.slug, spec.meta.title) },
    { rel: "next.config.mjs", contents: nextConfig },
    { rel: "postcss.config.mjs", contents: postcssConfig },
    { rel: "tsconfig.json", contents: tsconfig },
    { rel: "next-env.d.ts", contents: nextEnv },
    { rel: ".gitignore", contents: gitignore },
    { rel: "app/globals.css", contents: css },
    { rel: "app/layout.tsx", contents: layoutTsx(spec.meta.title, spec.meta.description, spec.meta.language, spec.meta.themeColor) },
    { rel: "app/page.tsx", contents: page },
    { rel: "components/sections.tsx", contents: SECTIONS_TSX },
    { rel: "components/chrome.tsx", contents: CHROME_TSX },
    { rel: "lib/types.ts", contents: typesTs },
    { rel: "lib/site-spec.ts", contents: specModule },
    { rel: "README.md", contents: readme(spec, mode) },
  ];

  const result = await scaffoldProject({ projectDir, files });
  log.info("project written", {
    projectDir,
    files: result.written,
    changed: result.changed,
    mode,
    pageSource: useAi ? "ai" : "spec",
    sections: spec.sections.length,
  });
  return {
    projectDir,
    files: files.map((f) => f.rel),
    changed: result.changed,
    mode,
    pageSource: useAi ? "ai" : "spec",
  };
}

// -------------------------------------------------------------- spec module

/**
 * The spec is emitted as readable JSON-compatible TypeScript.
 *
 * Readable on purpose: `generated/<id>/lib/site-spec.ts` is the artefact a
 * reviewer should read to understand what the agent decided, and it is also
 * what a natural-language edit is applied to.
 */
export function renderSpecModule(spec: WebsiteSpec): string {
  const json = JSON.stringify(spec, null, 2);
  return `/**
 * The website specification.
 *
 * Generated by Sitewright from ${spec.meta.sourceUrl}.
 * Every visual token here was measured from the source page; every semantic
 * field (section kind, name, intent) was decided by ${spec.stats.model || "the model"}.
 *
 * This file is the single source of truth for the generated site. Editing it
 * and rebuilding is a legitimate way to change the output.
 */
import type { WebsiteSpec } from "./types";

export const siteSpec: WebsiteSpec = ${json};

export default siteSpec;
`;
}

// ------------------------------------------------------------------- pages

/**
 * Deterministic page: a straight projection of the composition list.
 *
 * The composition comes from the model (see `composePage`) but is validated
 * against the spec first, so the emitted file always references sections that
 * exist.
 */
function deterministicPage(
  spec: WebsiteSpec,
  composition: { kind: string; id: string; props?: Record<string, unknown> }[],
): string {
  const known = new Map(spec.sections.map((s) => [s.id, s]));
  const entries: { kind: string; id: string; props: Record<string, unknown> }[] = [];
  const seen = new Set<string>();
  for (const c of composition) {
    if (known.has(c.id) && !seen.has(c.id)) {
      entries.push({ kind: c.kind, id: c.id, props: c.props ?? {} });
      seen.add(c.id);
    }
  }
  for (const s of spec.sections) {
    if (!seen.has(s.id)) entries.push({ kind: s.kind, id: s.id, props: {} });
  }

  return `/**
 * Page composition.
 *
 * Order and grouping come from the model, validated against the specification
 * before emission. The components come from the generated section library, so
 * this file only decides *which* blocks appear and in *what order*.
 */
import { renderSection } from "../components/sections";
import { siteSpec } from "../lib/site-spec";
import type { CompositionEntry, SectionSpec } from "../lib/types";

const composition: CompositionEntry[] = ${JSON.stringify(entries, null, 2)};

function byId(id: string): SectionSpec | undefined {
  return siteSpec.sections.find((s) => s.id === id);
}

export default function Page() {
  return (
    <>
      {composition.map((entry) => {
        const section = byId(entry.id);
        return section ? renderSection(section) : null;
      })}
    </>
  );
}
`;
}

/**
 * Tidy up a model-authored page module.
 *
 * Two mechanical guards, because the model reliably gets these right in intent
 * and wrong in detail: strip markdown fences if it emitted them, and reject the
 * file outright if it tries to import anything outside the generated project.
 * Anything semantically wrong is left to the build + repair loop to catch.
 */
function normaliseAiPage(source: string): string {
  let s = source.trim();
  const fence = s.match(/^```(?:tsx|jsx|ts|js)?\s*\n([\s\S]*?)\n?```$/);
  if (fence) s = fence[1];
  const imports = s.match(/^\s*import\s+.*?from\s+["']([^"']+)["']/gm) ?? [];
  for (const line of imports) {
    const m = line.match(/["']([^"']+)["']/);
    if (!m) continue;
    const spec = m[1];
    const allowed = spec.startsWith(".") || spec.startsWith("@/");
    if (!allowed) {
      throw new Error(
        `The authored page imported "${spec}", which is not available in the generated project. Only relative imports of the generated modules are allowed.`,
      );
    }
  }
  if (!/export\s+default/.test(s)) {
    throw new Error("The authored page has no default export.");
  }
  return s + "\n";
}

// ------------------------------------------------------------------ readme

function readme(spec: WebsiteSpec, mode: GenerationMode): string {
  const byKind = new Map<string, number>();
  for (const s of spec.sections) byKind.set(s.kind, (byKind.get(s.kind) ?? 0) + 1);
  const inventory = Array.from(byKind.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([k, n]) => `| ${k} | ${n} |`)
    .join("\n");

  return `# ${spec.meta.title || "Generated site"}

Generated by **Sitewright** from <${spec.meta.sourceUrl}>.

This is a standalone Next.js + Tailwind project. It does **not** embed, proxy,
screenshot, or otherwise depend on the source site at runtime: every asset was
downloaded into \`public/assets/\` and every font, colour and spacing value is
expressed as a local design token.

## Run it

\`\`\`bash
npm install
npm run dev
\`\`\`

## Layout

| Path | What it is |
| --- | --- |
| \`lib/site-spec.ts\` | The WebsiteSpec. The single source of truth. |
| \`components/sections.tsx\` | Reusable section components, one per section kind. |
| \`components/chrome.tsx\` | Header and footer. |
| \`app/page.tsx\` | Page composition (${mode === "ai-page" ? "authored by the model" : "deterministic projection of the composition list"}). |
| \`app/globals.css\` | Design tokens emitted from the measurements. |

## Sections

| Kind | Count |
| --- | --- |
${inventory}

## Provenance

${spec.analysis.summary || "(no summary recorded)"}

${
  spec.analysis.warnings.length
    ? "### Known limitations\n\n" + spec.analysis.warnings.map((w) => `- ${w}`).join("\n")
    : ""
}
${
  spec.stats.assetsMissing
    ? `\n${spec.stats.assetsMissing} asset(s) could not be downloaded and are represented by placeholders.`
    : ""
}
${
  spec.meta.favicon
    ? `\nFavicon: \`${sanitizeCssValue(spec.meta.favicon, "not copied")}\``
    : ""
}
`;
}

export { renderGlobalsCss, SECTIONS_TSX, CHROME_TSX, CHROME_CSS };
export function projectPath(root: string, ...rest: string[]): string {
  return path.join(root, ...rest);
}
