/**
 * Project scaffolding.
 *
 * Dependency hoisting
 * -------------------
 * A generated project is a *real* Next.js project — its own `package.json`,
 * `tsconfig.json`, `next.config.mjs`, `postcss.config.mjs`, `app/`, and
 * `components/` — but it does not run `npm install`. `next`, `react`, `react-dom`
 * and `tailwindcss` resolve from the repository root's `node_modules` because
 * Node walks up the directory tree, and the build is invoked as
 * `<repo>/node_modules/.bin/next build` with the generated project as cwd.
 *
 * This is what makes a generation take ~15s instead of ~3 minutes, and it is why
 * the pipeline is viable on free models. The trade-off is stated plainly in
 * docs/architecture.md: a generated project is runnable here, not necessarily
 * runnable after being copied somewhere else without an install.
 */

import fsp from "node:fs/promises";
import path from "node:path";
import { createLogger } from "../logger";

const log = createLogger("generator/scaffold");

export interface ScaffoldFile {
  /** Path relative to the project root. */
  rel: string;
  contents: string;
}

const PKG_NAME = (slug: string) => `sitewright-${slug}`.slice(0, 60);

export function packageJson(slug: string, title: string): string {
  return `${JSON.stringify(
    {
      name: PKG_NAME(slug),
      version: "0.1.0",
      private: true,
      description: `Standalone Next.js site generated by Sitewright from ${title}`,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        typecheck: "tsc --noEmit",
      },
      // Declared for documentation and for running the project on its own.
      // The build inside Sitewright resolves these from the repository root.
      dependencies: {
        next: "^15.5.26",
        react: "^19.1.0",
        "react-dom": "^19.1.0",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4.1.13",
        tailwindcss: "^4.1.13",
        typescript: "^5.9.2",
        "@types/node": "^22.18.0",
        "@types/react": "^19.1.0",
        "@types/react-dom": "^19.1.0",
      },
    },
    null,
    2,
  )}\n`;
}

export const nextConfig = `/** @type {import('next').NextConfig} */
export default {
  reactStrictMode: true,
  // The generated site is fully static; no server actions, no dynamic data.
  output: "standalone",
  // The validator's repair loop works from real compiler diagnostics, so the
  // build must not paper over type errors.
  typescript: { ignoreBuildErrors: false },
  eslint: { ignoreDuringBuilds: true },
};
`;

export const postcssConfig = `export default {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n`;

export const tsconfig = `${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      lib: ["dom", "dom.iterable", "ES2022"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  },
  null,
  2,
)}\n`;

export const nextEnv = `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// NOTE: This file should not be edited.\n`;

export const gitignore = `node_modules\n.next\nout\n*.tsbuildinfo\n.DS_Store\n`;

export function layoutTsx(title: string, description: string, language: string, themeColor: string): string {
  return `import "./globals.css";
import { SiteHeader, SiteFooter } from "../components/chrome";

export const metadata = {
  title: ${JSON.stringify(title || "Website")},
  description: ${JSON.stringify(description)},
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: ${JSON.stringify(themeColor || "#111827")},
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang=${JSON.stringify(language || "en")}>
      <body className="min-h-screen antialiased">
        <SiteHeader />
        <main id="main">{children}</main>
        <SiteFooter />
      </body>
    </html>
  );
}
`;
}

/** Type declarations mirrored from the WebsiteSpec schema, for the standalone project. */
export const typesTs = `/**
 * Site types.
 *
 * These mirror src/lib/spec/schema.ts. They are duplicated rather than
 * imported so the generated project is genuinely self-contained: copying
 * generated/<id>/ to another machine and running \`npm install\` gives a working
 * site with no dependency on this repository.
 */

export type AssetRef = {
  localPath: string;
  sourceUrl?: string;
  alt: string;
  width?: number;
  height?: number;
  intrinsicWidth?: number;
  intrinsicHeight?: number;
  missing: boolean;
  kind: "image" | "svg" | "video" | "icon" | "font" | "other";
};

export type TextBlock = {
  text: string;
  level: number;
  align: "left" | "center" | "right";
  color?: string;
  fontSize?: number;
  fontWeight?: number;
};

export type Link = {
  label: string;
  href: string;
  primary: boolean;
  external: boolean;
};

export type Item = {
  title: string;
  body: string;
  meta: string;
  price: string;
  bullets: string[];
  image?: AssetRef;
  icon?: AssetRef;
  link?: Link;
  badge: string;
};

export type SectionStyle = {
  background: string;
  color: string;
  paddingY: number;
  paddingX: number;
  maxWidth?: number;
  align: "left" | "center";
  columns: number;
  gap: number;
  split: "stack" | "side";
  side: "text-first" | "media-first";
  borderTop: string;
  radius: string;
};

export type SectionSpec = {
  id: string;
  kind: string;
  name: string;
  intent: string;
  heading?: TextBlock;
  subheading?: TextBlock;
  items: Item[];
  links: Link[];
  cta?: Link;
  media?: AssetRef;
  backgroundMedia?: AssetRef;
  style: SectionStyle;
  measuredHeight?: number;
  measuredWidth?: number;
  order: number;
  lowConfidence: boolean;
  sourceTag: string;
  sourceSelector: string;
};

export type NavSpec = {
  brand: string;
  brandText: string;
  logo?: AssetRef;
  links: Link[];
  cta?: Link;
  variant: "logo-links" | "logo-links-cta" | "centered" | "minimal" | "stacked";
  background: string;
  sticky: boolean;
  borderBottom: string;
  height?: number;
};

export type FooterSpec = {
  brand: string;
  brandText: string;
  logo?: AssetRef;
  tagline: string;
  columns: { heading: string; links: Link[] }[];
  legal: Link[];
  social: Link[];
  variant: "columns" | "simple" | "centered";
  background: string;
  color: string;
  paddingY: number;
  copyright: string;
};

export type FontToken = {
  family: string;
  size: number;
  weight: number;
  lineHeight: number;
  letterSpacing: string;
  transform: string;
  italic: boolean;
};

export type ThemeSpec = {
  mode: "light" | "dark";
  tokens: {
    background: string;
    surface: string;
    surfaceAlt: string;
    text: string;
    textMuted: string;
    primary: string;
    onPrimary: string;
    border: string;
    accent: string;
  };
  fonts: { heading: FontToken; body: FontToken };
  radius: { sm: string; md: string; lg: string; pill: string };
  shadow: { sm: string; md: string; lg: string };
  containerWidth: number;
  baseFontSize: number;
  headingWeight: number;
  borderWidth: string;
  provenance: { tokens: string; fonts: string; radius: string };
};

export type WebsiteSpec = {
  specVersion: 1;
  meta: {
    sourceUrl: string;
    finalUrl: string;
    title: string;
    description: string;
    language: string;
    favicon: string;
    themeColor: string;
    generator: string;
  };
  theme: ThemeSpec;
  nav: NavSpec | null;
  sections: SectionSpec[];
  footer: FooterSpec | null;
  responsive: {
    observedViewports: { name: string; width: number; height: number }[];
    mobileReordersNav: boolean;
    mobileHidesColumns: boolean;
    containerGutter: number;
  };
  analysis: {
    summary: string;
    designLanguage: string;
    audience: string;
    warnings: string[];
  };
  stats: {
    model: string;
    analyzedAt: string;
    durationMs: number;
    sectionCount: number;
    assetCount: number;
    assetsMissing: number;
    modelTrail: string[];
  };
};

/** One entry in the page composition. \`id\` refers to a section in the spec. */
export type CompositionEntry = { kind: string; id: string; props?: Record<string, unknown> };
`;

/** Write a file only when the content changed, so rebuilds stay fast. */
async function writeIfChanged(abs: string, contents: string): Promise<boolean> {
  try {
    const existing = await fsp.readFile(abs, "utf8");
    if (existing === contents) return false;
  } catch {
    /* new file */
  }
  await fsp.mkdir(path.dirname(abs), { recursive: true });
  await fsp.writeFile(abs, contents, "utf8");
  return true;
}

export interface ScaffoldResult {
  projectDir: string;
  written: number;
  changed: number;
}

export async function scaffoldProject(args: {
  projectDir: string;
  files: ScaffoldFile[];
  clean?: boolean;
}): Promise<ScaffoldResult> {
  const { projectDir, files } = args;
  if (args.clean) {
    await fsp.rm(path.join(projectDir, "app"), { recursive: true, force: true });
    await fsp.rm(path.join(projectDir, "components"), { recursive: true, force: true });
    await fsp.rm(path.join(projectDir, "lib"), { recursive: true, force: true });
  }
  await fsp.mkdir(projectDir, { recursive: true });
  let changed = 0;
  for (const f of files) {
    const abs = path.join(projectDir, f.rel);
    if (await writeIfChanged(abs, f.contents)) changed++;
  }
  log.debug("scaffold written", { files: files.length, changed });
  return { projectDir, written: files.length, changed };
}
