/**
 * The generated project's section library.
 *
 * This is emitted verbatim into `components/sections.tsx` of every generated
 * site. Two properties matter:
 *
 *   1. **Reusable.** Each section kind is a component that takes a `SectionSpec`
 *      and renders it. A page is a list of specs. Adding a kind means adding one
 *      component, not editing twenty call sites.
 *
 *   2. **Spec-driven.** Colours, padding, column counts, alignment, split
 *      direction and borders all come from the measured section style, not from
 *      hardcoded class strings. That is what makes the same library render a
 *      dense enterprise table and an airy editorial page.
 *
 * Plain `<img>` rather than `next/image`: the clone must build and run without
 * a native image optimiser, and every asset is already local with its
 * dimensions recorded, so the layout is stable either way.
 */

export const SECTIONS_TSX = String.raw`/**
 * Section components. Generated by Sitewright — edit the spec, not this file,
 * unless you want to change the component vocabulary.
 */
import type { AssetRef, Item, Link, SectionSpec } from "../lib/types";

/* ------------------------------------------------------------------ utils */

function cx(...parts: (string | false | null | undefined)[]): string {
  return parts.filter(Boolean).join(" ");
}

function columnsVars(cols: number): Record<string, string> {
  const n = Math.max(1, Math.min(6, cols));
  return {
    ["--sw-cols" as string]: String(n),
    ["--sw-cols-md" as string]: String(Math.min(n, 2)),
  };
}

function isUsable(a: AssetRef | undefined): a is AssetRef {
  return !!a && !!a.localPath && a.localPath.length > 0;
}

/** Only relative, single-slash-prefixed paths are ever emitted into src. */
function assetPath(a: AssetRef): string {
  const p = a.localPath.startsWith("/") ? a.localPath : "/" + a.localPath;
  return p.replace(/\/{2,}/g, "/");
}

function firstSentence(text: string, max = 180): string {
  const t = (text || "").replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  const stop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf(" "));
  return (stop > max * 0.6 ? cut.slice(0, stop) : cut).trim() + "…";
}

/* -------------------------------------------------------------- primitives */

function Section({
  s,
  children,
  className,
  as: Tag = "section",
}: {
  s: SectionSpec;
  children: React.ReactNode;
  className?: string;
  as?: "section" | "div" | "header" | "footer" | "aside";
}) {
  const st = s.style;
  const bg = st.background && st.background !== "transparent" ? st.background : undefined;
  return (
    <Tag
      id={s.id}
      className={cx("sw-section", className)}
      data-kind={s.kind}
      style={{
        background: bg,
        color: st.color && st.color !== "inherit" ? st.color : undefined,
        paddingTop: st.paddingY,
        paddingBottom: st.paddingY,
        borderTop: st.borderTop && st.borderTop !== "none" ? st.borderTop : undefined,
        borderRadius: st.radius && st.radius !== "0px" ? st.radius : undefined,
      }}
    >
      <div className="sw-container" style={st.maxWidth ? { maxWidth: st.maxWidth + "px" } : undefined}>
        {children}
      </div>
    </Tag>
  );
}

function Heading({ s, level }: { s: SectionSpec; level?: 1 | 2 | 3 }) {
  const h = s.heading;
  if (!h || !h.text) return null;
  const tag = (level ?? (h.level === 1 ? 1 : 2)) as 1 | 2 | 3;
  const Tag = ("h" + tag) as "h1" | "h2" | "h3";
  const cls = tag === 1 ? "text-4xl sm:text-5xl" : tag === 2 ? "text-3xl sm:text-4xl" : "text-2xl";
  return (
    <Tag
      className={cls}
      style={{
        textAlign: h.align,
        ...(h.fontSize ? { fontSize: h.fontSize + "px" } : {}),
        ...(h.fontWeight ? { fontWeight: h.fontWeight } : {}),
        ...(h.color ? { color: h.color } : {}),
      }}
    >
      {h.text}
    </Tag>
  );
}

function Sub({ s }: { s: SectionSpec }) {
  const t = s.subheading;
  if (!t || !t.text) return null;
  return (
    <p
      className="mt-4 text-lg"
      style={{ textAlign: t.align, color: "var(--color-muted)", maxWidth: "62ch" }}
    >
      {t.text}
    </p>
  );
}

/**
 * Kinds that place their own media, so the lead image must not be repeated, and
 * kinds where a lead image makes no sense at all.
 *
 * Every other kind is expected to show the section's image here. Without this,
 * a section whose image was measured, downloaded into the generated public
 * assets directory and recorded in the spec simply never rendered it - which is
 * exactly the kind of silent content loss that makes a clone look empty while
 * every log line says the run succeeded.
 */
const MEDIA_IS_PLACED_BY_KIND = new Set(["hero", "video", "announcement", "cta"]);
const NEVER_LEADS = new Set(["footer", "menu", "logo-strip", "stats", "testimonials", "pricing", "faq"]);

/**
 * Minimum rendered width for an image to count as a section's lead visual.
 *
 * Every section ends up with *an* image on any real site, but most of them are
 * 50px avatars and 150px thumbnails that belong to an item, not to the section
 * as a whole. Promoting those added a full-width band per section and roughly
 * doubled the page height. A lead visual is a banner, so the threshold is the
 * width above which the source treated it as one.
 */
const LEAD_MEDIA_MIN_WIDTH = 560;

/** The section's own image, if it is big enough and shaped like a banner. */
function leadMedia(s: SectionSpec): AssetRef | undefined {
  if (MEDIA_IS_PLACED_BY_KIND.has(s.kind) || NEVER_LEADS.has(s.kind)) return undefined;
  const a = s.media;
  if (!isUsable(a) || a.kind === "svg") return undefined;
  const width = Math.max(a.width ?? 0, a.intrinsicWidth ?? 0);
  if (width < LEAD_MEDIA_MIN_WIDTH) return undefined;
  // A very wide image is a banner, not a photograph: a shallower ratio both
  // matches how such images are used and stops it dominating the section.
  return width >= 1000 ? { ...a, kind: a.kind } : a;
}

/** Aspect ratio for the lead image, from its measured shape. */
function leadRatio(a: AssetRef): string {
  const w = Math.max(a.width ?? 0, a.intrinsicWidth ?? 0);
  const h = Math.max(a.height ?? 0, a.intrinsicHeight ?? 0);
  if (!w || !h) return "16 / 9";
  const r = w / h;
  if (r >= 2.4) return "21 / 9";
  if (r >= 1.9) return "2 / 1";
  if (r < 0.85) return "4 / 5";
  return "16 / 9";
}

function Intro({ s, centered }: { s: SectionSpec; centered?: boolean }) {
  const align = centered ?? (s.style.align === "center" || s.heading?.align === "center");
  const lead = leadMedia(s);
  const leadNode = lead ? (
    <Media a={lead} ratio={leadRatio(lead)} sizes="(min-width: 1024px) 62vw, 100vw" priority />
  ) : null;
  if (!s.heading?.text && !s.subheading?.text && !leadNode) return null;
  return (
    <header className={cx(leadNode ? "mb-8" : "mb-10", align && "text-center")}>
      <Heading s={s} />
      <Sub s={s} />
      {leadNode}
      <Actions s={s} className={align ? "mt-6 justify-center" : "mt-6"} />
    </header>
  );
}

function Actions({ s, className }: { s: SectionSpec; className?: string }) {
  const links = [s.cta, ...s.links.filter((l) => l.primary)].filter(Boolean) as Link[];
  if (!links.length) return null;
  return (
    <div className={cx("mt-8 flex flex-wrap gap-3", className)}>
      {links.slice(0, 3).map((l, i) => (
        <a
          key={i}
          className={cx("sw-btn", l.primary || i === 0 ? "sw-btn-primary" : "sw-btn-ghost")}
          href={l.href || "#"}
          {...(l.external ? { target: "_blank", rel: "noopener noreferrer" } : {})}
        >
          {l.label}
        </a>
      ))}
    </div>
  );
}

function Media({
  a,
  className,
  ratio = "4 / 3",
  sizes = "(min-width: 1024px) 45vw, 100vw",
  priority,
}: {
  a: AssetRef | undefined;
  className?: string;
  ratio?: string;
  sizes?: string;
  priority?: boolean;
}) {
  if (!isUsable(a)) return null;
  if (a.kind === "video") {
    return (
      <video
        className={cx("w-full rounded-lg", className)}
        style={{ aspectRatio: ratio, objectFit: "cover", background: "var(--color-surface-alt)" }}
        controls
        preload={priority ? "metadata" : "none"}
        poster={undefined}
      >
        <source src={assetPath(a)} />
      </video>
    );
  }
  return (
    <img
      src={assetPath(a)}
      alt={a.alt || ""}
      className={cx("w-full rounded-lg", className)}
      style={{
        aspectRatio: ratio,
        objectFit: "cover",
        background: "var(--color-surface-alt)",
      }}
      // Dimensions are preserved in the element so the browser reserves the
      // right box before the file decodes, which is what keeps the generated
      // page from reflowing as images arrive.
      width={a.intrinsicWidth || a.width || undefined}
      height={a.intrinsicHeight || a.height || undefined}
      loading={priority ? "eager" : "lazy"}
      decoding="async"
      {...(typeof a.intrinsicWidth === "number" && typeof a.intrinsicHeight === "number"
        ? { sizes }
        : {})}
    />
  );
}

function Card({
  children,
  className,
  flat,
}: {
  children: React.ReactNode;
  className?: string;
  flat?: boolean;
}) {
  return (
    <div
      className={cx(
        flat ? "sw-card-flat" : "sw-card",
        "p-6",
        className,
      )}
    >
      {children}
    </div>
  );
}

function ItemImage({ item, ratio }: { item: Item; ratio?: string }) {
  const a = item.image ?? item.icon;
  if (!isUsable(a)) return null;
  const isIcon = a === item.icon && a.kind === "svg";
  if (isIcon) {
    return (
      <img
        src={assetPath(a)}
        alt={a.alt || ""}
        className="mb-4 h-10 w-10"
        style={{ objectFit: "contain" }}
        width={a.intrinsicWidth || 40}
        height={a.intrinsicHeight || 40}
        loading="lazy"
        decoding="async"
      />
    );
  }
  return <Media a={a} ratio={ratio ?? "16 / 10"} sizes="(min-width: 1024px) 30vw, 100vw" />;
}

function ItemText({ item, dense }: { item: Item; dense?: boolean }) {
  return (
    <>
      {item.badge ? <span className="sw-badge">{item.badge}</span> : null}
      {item.title ? (
        <h3 className={dense ? "text-base font-semibold" : "text-lg font-semibold"}>{item.title}</h3>
      ) : null}
      {item.body ? (
        <p className="mt-2 text-[0.95rem] leading-relaxed" style={{ color: "var(--color-muted)" }}>
          {item.body}
        </p>
      ) : null}
      {item.bullets.length ? (
        <ul className="mt-3 space-y-1.5 text-sm" style={{ color: "var(--color-muted)" }}>
          {item.bullets.slice(0, 8).map((b, i) => (
            <li key={i} className="flex gap-2">
              <span aria-hidden="true" style={{ color: "var(--color-primary)" }}>
                ✓
              </span>
              <span>{b}</span>
            </li>
          ))}
        </ul>
      ) : null}
    </>
  );
}

/* ---------------------------------------------------------------- sections */

export function Announcement({ s }: { s: SectionSpec }) {
  const link = s.links[0] ?? s.cta;
  return (
    <Section s={s} className="sw-announce">
      <p
        className="text-center text-sm"
        style={{ color: s.style.color !== "inherit" ? undefined : "var(--color-primary)" }}
      >
        {s.heading?.text ?? ""}
        {s.subheading?.text ? <span style={{ color: "var(--color-muted)" }}> {s.subheading.text}</span> : null}
        {link?.label ? (
          <a className="ml-2 font-semibold underline" href={link.href || "#"}>
            {link.label}
          </a>
        ) : null}
      </p>
    </Section>
  );
}

export function Hero({ s }: { s: SectionSpec }) {
  const st = s.style;
  const hasMedia = isUsable(s.media);
  const side = st.split === "side" && hasMedia;
  const copy = (
    <div className={side ? (st.side === "media-first" ? "lg:order-2" : "") : ""}>
      <Heading s={s} level={1} />
      <Sub s={s} />
      <Actions s={s} />
      {s.items.length ? (
        <ul data-sw-grid="" className="mt-8 gap-3" style={columnsVars(2)}>
          {s.items.slice(0, 6).map((it, i) => (
            <li key={i} className="flex items-start gap-2 text-sm">
              <span aria-hidden="true" style={{ color: "var(--color-primary)" }}>
                ✓
              </span>
              <span>{it.title || firstSentence(it.body, 60)}</span>
            </li>
          ))}
        </ul>
      ) : null}
    </div>
  );
  const picture = hasMedia ? (
    <div className={side ? (st.side === "media-first" ? "lg:order-1" : "") : "mt-10"}>
      <Media a={s.media} ratio="4 / 3" sizes="(min-width: 1024px) 48vw, 100vw" priority />
    </div>
  ) : null;
  return (
    <Section s={s} as="header" className="sw-hero">
      {isUsable(s.backgroundMedia) ? (
        <div
          aria-hidden="true"
          className="sw-hero-bg"
          style={{ backgroundImage: "url(" + JSON.stringify(assetPath(s.backgroundMedia as AssetRef)) + ")" }}
        />
      ) : null}
      <div className={cx(side ? "grid items-center gap-10 lg:grid-cols-2" : "")}>
        {copy}
        {picture}
      </div>
    </Section>
  );
}

export function LogoStrip({ s }: { s: SectionSpec }) {
  const images = s.items.map((i) => i.image).filter(isUsable);
  if (images.length) {
    return (
      <Section s={s}>
        <p
          className="mb-6 text-center text-sm font-medium uppercase tracking-wider"
          style={{ color: "var(--color-muted)" }}
        >
          {s.heading?.text ?? s.subheading?.text ?? ""}
        </p>
        <ul data-sw-grid="" className="grid items-center gap-8 opacity-80" style={columnsVars(Math.min(images.length, 6))}>
          {images.slice(0, 12).map((a, i) => (
            <li key={i} className="flex items-center justify-center">
              <img
                src={assetPath(a)}
                alt={a.alt || ""}
                className="max-h-10 w-auto"
                style={{ objectFit: "contain", filter: "grayscale(1)" }}
                width={a.intrinsicWidth || undefined}
                height={a.intrinsicHeight || 40}
                loading="lazy"
                decoding="async"
              />
            </li>
          ))}
        </ul>
      </Section>
    );
  }
  return (
    <Section s={s}>
      <p className="text-center text-sm" style={{ color: "var(--color-muted)" }}>
        {s.heading?.text ?? ""}
      </p>
      <ul
        data-sw-grid=""
        className="gap-6 text-center text-lg font-semibold opacity-70"
        style={columnsVars(Math.min(Math.max(s.items.length, 2), 6))}
      >
        {s.items.slice(0, 12).map((it, i) => (
          <li key={i}>{it.title}</li>
        ))}
      </ul>
    </Section>
  );
}

export function FeatureGrid({ s }: { s: SectionSpec }) {
  const withImage = s.items.some((i) => isUsable(i.image) && i.image?.kind !== "svg");
  return (
    <Section s={s}>
      <Intro s={s} />
      <ul data-sw-grid="" className="grid gap-6" style={columnsVars(s.style.columns)}>
        {s.items.slice(0, 12).map((it, i) => (
          <li key={i}>
            <Card className="h-full">
              {withImage && isUsable(it.image) && it.image.kind !== "svg" ? (
                <div className="mb-4">
                  <ItemImage item={it} ratio="16 / 9" />
                </div>
              ) : null}
              <ItemImage item={it} />
              <ItemText item={it} />
            </Card>
          </li>
        ))}
      </ul>
    </Section>
  );
}

export function Stats({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} centered={s.style.align === "center"} />
      <dl data-sw-grid="" className="grid gap-8 text-center" style={columnsVars(s.style.columns || s.items.length)}>
        {s.items.slice(0, 8).map((it, i) => {
          const [value, ...rest] = (it.title || it.body || "").split(/\s{2,}|\s*\|\s*|\s+—\s+/);
          const label = rest.join(" ") || (it.title && it.body ? it.body : "");
          return (
            <div key={i}>
              <dt className="sr-only">{label || it.title}</dt>
              <dd>
                <span
                  className="block text-4xl font-bold tabular-nums sm:text-5xl"
                  style={{ color: "var(--color-primary)" }}
                >
                  {it.price || value}
                </span>
                {label ? (
                  <span className="mt-2 block text-sm" style={{ color: "var(--color-muted)" }}>
                    {label}
                  </span>
                ) : null}
              </dd>
            </div>
          );
        })}
      </dl>
    </Section>
  );
}

export function Showcase({ s }: { s: SectionSpec }) {
  // Alternate sides only when every shown item actually has an image. A
  // two-column grid around an image-less item renders a permanently empty half,
  // which reads as a broken layout rather than as a section without pictures.
  const shown = s.items.slice(0, 8);
  const alternating = shown.length > 0 && shown.every((it) => isUsable(it.image ?? it.icon));
  return (
    <Section s={s}>
      <Intro s={s} />
      <div className={alternating ? "space-y-16" : "space-y-12"}>
        {shown.map((it, i) => (
          <article
            key={i}
            className={alternating ? "grid items-center gap-8 md:grid-cols-2" : "max-w-3xl"}
          >
            {alternating ? (
              <div className={i % 2 === 1 ? "md:order-2" : ""}>
                <ItemImage item={it} ratio="4 / 3" />
              </div>
            ) : (
              <ItemImage item={it} ratio="16 / 9" />
            )}
            <div>
              <ItemText item={it} />
              {it.link?.label ? (
                <a
                  className="mt-4 inline-block font-semibold"
                  style={{ color: "var(--color-primary)" }}
                  href={it.link.href || "#"}
                >
                  {it.link.label} →
                </a>
              ) : null}
            </div>
          </article>
        ))}
      </div>
    </Section>
  );
}

export function Gallery({ s }: { s: SectionSpec }) {
  const cols = s.style.columns >= 3 ? 3 : s.style.columns;
  return (
    <Section s={s}>
      <Intro s={s} />
      <ul data-sw-grid="" className="grid gap-4" style={columnsVars(cols)}>
        {s.items.slice(0, 18).map((it, i) => (
          <li key={i}>
            <figure className="sw-card overflow-hidden p-0">
              <Media a={it.image} ratio="3 / 2" sizes="(min-width: 1024px) 30vw, 100vw" />
              {it.title ? (
                <figcaption className="p-4 text-sm font-medium">{it.title}</figcaption>
              ) : null}
            </figure>
          </li>
        ))}
      </ul>
    </Section>
  );
}

export function Menu({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} />
      <ul className="divide-y" style={{ borderColor: "var(--color-border)" }}>
        {s.items.slice(0, 24).map((it, i) => (
          <li key={i} className="flex items-baseline justify-between gap-6 py-4">
            <div>
              {it.title ? <h3 className="font-semibold">{it.title}</h3> : null}
              {it.body ? (
                <p className="mt-1 text-sm" style={{ color: "var(--color-muted)" }}>
                  {it.body}
                </p>
              ) : null}
            </div>
            {it.price ? (
              <span className="shrink-0 font-semibold tabular-nums" style={{ color: "var(--color-primary)" }}>
                {it.price}
              </span>
            ) : null}
          </li>
        ))}
      </ul>
    </Section>
  );
}

export function Testimonials({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} />
      <ul data-sw-grid="" className="grid gap-6" style={columnsVars(s.style.columns || 3)}>
        {s.items.slice(0, 12).map((it, i) => (
          <li key={i}>
            <figure className="sw-card flex h-full flex-col p-6">
              <blockquote className="flex-1 text-[0.98rem] leading-relaxed">
                {it.body || it.title}
              </blockquote>
              <figcaption className="mt-5 flex items-center gap-3">
                {isUsable(it.image) ? (
                  <img
                    src={assetPath(it.image)}
                    alt=""
                    className="h-10 w-10 rounded-full"
                    style={{ objectFit: "cover" }}
                    width={40}
                    height={40}
                    loading="lazy"
                    decoding="async"
                  />
                ) : null}
                <span>
                  <span className="block text-sm font-semibold">{it.title}</span>
                  {it.meta ? (
                    <span className="block text-xs" style={{ color: "var(--color-muted)" }}>
                      {it.meta}
                    </span>
                  ) : null}
                </span>
              </figcaption>
            </figure>
          </li>
        ))}
      </ul>
    </Section>
  );
}

export function Pricing({ s }: { s: SectionSpec }) {
  const cta = s.links.filter((l) => l.primary);
  return (
    <Section s={s}>
      <Intro s={s} centered />
      <ul data-sw-grid="" className="grid items-start gap-6" style={columnsVars(s.style.columns || 3)}>
        {s.items.slice(0, 6).map((it, i) => (
          <li key={i}>
            <Card
              className="flex h-full flex-col"
            >
              {it.badge ? (
                <span className="sw-badge mb-3 self-start" style={{ color: "var(--color-primary)" }}>
                  {it.badge}
                </span>
              ) : null}
              <h3 className="text-lg font-semibold">{it.title}</h3>
              {it.price ? (
                <p className="mt-2 text-3xl font-bold tabular-nums">{it.price}</p>
              ) : null}
              {it.body ? (
                <p className="mt-2 text-sm" style={{ color: "var(--color-muted)" }}>
                  {it.body}
                </p>
              ) : null}
              {it.bullets.length ? (
                <ul className="mt-4 space-y-2 text-sm" style={{ color: "var(--color-muted)" }}>
                  {it.bullets.slice(0, 10).map((b, bi) => (
                    <li key={bi} className="flex gap-2">
                      <span aria-hidden="true" style={{ color: "var(--color-primary)" }}>
                        ✓
                      </span>
                      <span>{b}</span>
                    </li>
                  ))}
                </ul>
              ) : null}
              {cta[i] ? (
                <a
                  className={cx("sw-btn mt-6 w-full", cta[i].primary ? "sw-btn-primary" : "sw-btn-ghost")}
                  href={cta[i].href || "#"}
                >
                  {cta[i].label}
                </a>
              ) : null}
            </Card>
          </li>
        ))}
      </ul>
    </Section>
  );
}

/**
 * FAQ uses native <details>/<summary>: no client JavaScript, keyboard
 * accessible, and it works before hydration.
 */
export function Faq({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <div className="mx-auto max-w-3xl">
        <Intro s={s} centered={s.style.align === "center"} />
        <ul className="space-y-3">
          {s.items.slice(0, 20).map((it, i) => {
            const q = it.title || firstSentence(it.body, 90);
            const a = it.body && it.body !== q ? it.body : "";
            return (
              <li key={i} className="sw-card overflow-hidden">
                <details className="sw-faq">
                  <summary>
                    <span>{q}</span>
                    <span aria-hidden="true" className="sw-faq-icon">
                      +
                    </span>
                  </summary>
                  {a ? <div className="sw-faq-body">{a}</div> : null}
                </details>
              </li>
            );
          })}
        </ul>
      </div>
    </Section>
  );
}

export function Team({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} centered={s.style.align === "center"} />
      <ul data-sw-grid="" className="grid gap-8 text-center" style={columnsVars(s.style.columns || 4)}>
        {s.items.slice(0, 16).map((it, i) => (
          <li key={i}>
            {isUsable(it.image) ? (
              <img
                src={assetPath(it.image)}
                alt={it.image?.alt || ""}
                className="mx-auto mb-4 aspect-square w-full max-w-[200px] rounded-lg"
                style={{ objectFit: "cover", background: "var(--color-surface-alt)" }}
                width={it.image?.intrinsicWidth || 200}
                height={it.image?.intrinsicHeight || 200}
                loading="lazy"
                decoding="async"
              />
            ) : null}
            <h3 className="font-semibold">{it.title}</h3>
            {it.meta ? (
              <p className="text-sm" style={{ color: "var(--color-primary)" }}>
                {it.meta}
              </p>
            ) : null}
            {it.body ? (
              <p className="mt-1 text-sm" style={{ color: "var(--color-muted)" }}>
                {it.body}
              </p>
            ) : null}
          </li>
        ))}
      </ul>
    </Section>
  );
}

export function Timeline({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} />
      <ol className="relative space-y-10 border-l pl-8" style={{ borderColor: "var(--color-border)" }}>
        {s.items.slice(0, 12).map((it, i) => (
          <li key={i} className="relative">
            <span
              aria-hidden="true"
              className="absolute -left-[35px] flex h-3 w-3 rounded-full"
              style={{ background: "var(--color-primary)", top: "0.5rem" }}
            />
            {it.meta ? (
              <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--color-primary)" }}>
                {it.meta}
              </p>
            ) : null}
            <h3 className="text-lg font-semibold">{it.title}</h3>
            {it.body ? (
              <p className="mt-1 text-[0.95rem]" style={{ color: "var(--color-muted)" }}>
                {it.body}
              </p>
            ) : null}
          </li>
        ))}
      </ol>
    </Section>
  );
}

export function CtaBand({ s }: { s: SectionSpec }) {
  return (
    <Section s={s} className="sw-cta-band">
      <div className="mx-auto max-w-3xl text-center">
        <Heading s={s} />
        <Sub s={s} />
        <Actions s={s} className="justify-center" />
      </div>
    </Section>
  );
}

export function RichText({ s }: { s: SectionSpec }) {
  const paragraphs = [
    s.subheading?.text ?? "",
    ...s.items.map((i) => i.body).filter(Boolean),
  ].filter((p) => p && p.length > 2);
  return (
    <Section s={s}>
      <div className="sw-prose mx-auto max-w-3xl">
        <Heading s={s} />
        {paragraphs.slice(0, 10).map((p, i) => (
          <p key={i} style={{ color: "var(--color-muted)" }}>
            {p}
          </p>
        ))}
        {s.links.length ? (
          <ul className="mt-6 flex flex-wrap gap-4">
            {s.links.slice(0, 6).map((l, i) => (
              <li key={i}>
                <a className="font-semibold" style={{ color: "var(--color-primary)" }} href={l.href || "#"}>
                  {l.label}
                </a>
              </li>
            ))}
          </ul>
        ) : null}
      </div>
    </Section>
  );
}

/**
 * Forms are rendered as presentational markup. Nothing is submitted anywhere:
 * the generated site has no backend, and pretending otherwise would be a
 * privacy and security liability.
 */
export function FormBlock({ s }: { s: SectionSpec }) {
  const cta = s.links.find((l) => l.primary) ?? s.cta;
  return (
    <Section s={s}>
      <div className="mx-auto max-w-xl text-center">
        <Heading s={s} />
        <Sub s={s} />
        {/* No onSubmit. A handler cannot be attached to a Server Component's
             markup, and every section here is a Server Component, so the
             attribute is not merely redundant - Next.js fails the prerender with
             "Event handlers cannot be passed to Client Component props". The form
             is inert by construction: there is no action attribute and the input
             is not required, so submitting it reloads the page with nothing
             sent. The
             same bug sat in any section the analyzer happened to classify as a
             form, so it only appeared on whichever site produced one. */}
        <form className="sw-card mt-8 space-y-4 p-6 text-left" method="post" action="">
          {s.items.slice(0, 5).map((it, i) => (
            <label key={i} className="block text-sm font-medium">
              {it.title || (i === 0 ? "Email address" : "Field " + (i + 1))}
              <input
                type={i === 0 ? "email" : "text"}
                name={"field-" + i}
                className="sw-input mt-1 w-full"
                placeholder={it.body || ""}
                autoComplete={i === 0 ? "email" : "off"}
              />
            </label>
          ))}
          <button type="submit" className="sw-btn sw-btn-primary w-full">
            {cta?.label || "Submit"}
          </button>
          <p className="text-xs" style={{ color: "var(--color-muted)" }}>
            This form is a visual reconstruction and does not send data anywhere.
          </p>
        </form>
      </div>
    </Section>
  );
}

export function DataTable({ s }: { s: SectionSpec }) {
  const header = s.links.slice(0, 0);
  void header;
  return (
    <Section s={s}>
      <Intro s={s} />
      <div className="sw-card overflow-x-auto p-0">
        <table className="w-full text-left text-sm">
          <thead>
            <tr>
              {s.items.slice(0, 6).map((it, i) => (
                <th key={i} scope="col" className="px-4 py-3 font-semibold">
                  {it.title}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {(s.items[0]?.bullets ?? []).slice(0, 12).map((row, r) => (
              <tr key={r} className="sw-row">
                {s.items.slice(0, 6).map((it, c) => (
                  <td key={c} className="px-4 py-3" style={{ color: "var(--color-muted)" }}>
                    {c === 0 ? row : (it.bullets[r] ?? "")}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Section>
  );
}

export function VideoBlock({ s }: { s: SectionSpec }) {
  return (
    <Section s={s}>
      <Intro s={s} centered />
      <div className="mx-auto max-w-4xl">
        <Media a={s.media} ratio="16 / 9" sizes="(min-width: 1024px) 60vw, 100vw" priority />
      </div>
    </Section>
  );
}

/**
 * A footer-shaped section.
 *
 * Plans routinely label the bottom band "footer", and before this component
 * existed such a section fell through the registry to Unclassified - an
 * ordinary content block rendered alongside the chrome footer's SiteFooter,
 * so the site ended up with two footers that disagreed. Rendering the section
 * itself as the footer keeps one definition on the page: the section's own
 * columns become the link columns, and the pattern otherwise matches the
 * chrome footer's visual language (surface tint, muted text, centred).
 */
export function FooterBlock({ s }: { s: SectionSpec }) {
  const columns = s.style.columns > 1 ? s.style.columns : 3;
  const last = [...s.items].pop();
  const cols = s.items.length ? s.items : [{ title: "", body: s.subheading?.text || "", meta: "", price: "", badge: "", bullets: [], link: { label: "", href: "#", primary: false, external: false } }];
  return (
    <Section s={s} as="footer">
      <Intro s={s} />
      <div data-sw-grid="" className="grid gap-8 md:grid-cols-2" style={columnsVars(columns)}>
        {cols.slice(0, 9).map((it, i) => (
          <nav key={i} aria-label={it.title || "Footer"}>
            {it.title ? <h3 className="mb-3 text-sm font-semibold uppercase tracking-wide">{it.title}</h3> : null}
            <ul className="space-y-2 text-sm" style={{ color: "var(--color-muted)" }}>
              {(it.bullets.length ? it.bullets : it.body ? [it.body] : []).slice(0, 8).map((b, j) => (
                <li key={j}>{b}</li>
              ))}
            </ul>
          </nav>
        ))}
      </div>
      {last?.body ? (
        <p className="mt-10 border-t pt-6 text-xs" style={{ color: "var(--color-muted)" }}>
          {last.body}
        </p>
      ) : null}
    </Section>
  );
}

/** Anything the classifier could not name still renders its real content. */
export function Unclassified({ s }: { s: SectionSpec }) {
  if (!s.items.length) {
    return (
      <Section s={s}>
        <div className="mx-auto max-w-3xl">
          <Heading s={s} />
          <Sub s={s} />
          <Actions s={s} />
        </div>
      </Section>
    );
  }
  return (
    <Section s={s}>
      <Intro s={s} />
      <div data-sw-grid="" className="grid gap-8" style={columnsVars(s.style.columns)}>
        {s.items.slice(0, 12).map((it, i) => (
          <article key={i} className={cx(s.style.columns <= 2 ? "sw-prose" : "")}>
            <ItemText item={it} />
            {it.link?.label ? (
              <a
                className="mt-2 inline-block font-semibold"
                style={{ color: "var(--color-primary)" }}
                href={it.link.href || "#"}
              >
                {it.link.label}
              </a>
            ) : null}
          </article>
        ))}
      </div>
    </Section>
  );
}

/** kind → component. A new kind is a new entry, nothing else to change. */
export const SECTION_COMPONENTS: Record<string, (props: { s: SectionSpec }) => React.ReactElement> = {
  announcement: Announcement,
  hero: Hero,
  logos: LogoStrip,
  features: FeatureGrid,
  stats: Stats,
  showcase: Showcase,
  gallery: Gallery,
  menu: Menu,
  testimonials: Testimonials,
  pricing: Pricing,
  faq: Faq,
  team: Team,
  timeline: Timeline,
  cta: CtaBand,
  richtext: RichText,
  form: FormBlock,
  table: DataTable,
  video: VideoBlock,
  footer: FooterBlock,
  unknown: Unclassified,
};

export function renderSection(s: SectionSpec): React.ReactElement {
  const Cmp = SECTION_COMPONENTS[s.kind] ?? Unclassified;
  return <Cmp key={s.id} s={s} />;
}
`;
